### PR TITLE
Changed personal page URL due to username change

### PR DESCRIPTION
**Pull request by Ra1ny-Yuki**

### CODE REVIEW

**Comment by alex3236** [comment]
actually github usernames are case insensitive (

**Comment by Ra1ny-Yuki** [comment]
> actually github usernames are case insensitive (

I have OCD xD

**Comment by alex3236** [comment]
> I have OCD xD

w

**Comment by Ra1ny-Yuki** [comment]
> actually github usernames are case insensitive (

and I wonder if it will cause anthor author in `meta` branch appears because of url change (may not? i havent check action scripts yet)

**Pull request merged**
