### PR TITLE
fix(meta): fix introduction for old plugins

### PR DESCRIPTION
**Pull request by alex3236**
Fix introduction of old plugins, by targeting introduction to their README file.

### CODE REVIEW

**Comment by AnzhiZhang** [comment]
report 怎么寄了

**Comment by alex3236** [comment]
> report 怎么寄了

当时加了个最多16个的限制

**Comment by Fallen-Breath** [comment]
So now the `introduction` field is required, not optional, right? If so, I'll suggest to update related mcdr docs as well

For the PR modification itself, lgtm as long as all those readme file names / paths are correct

**Comment by alex3236** [comment]
> So now the `introduction` field is required, not optional, right?

Introduction should provide at least in one language now

> I'll suggest to update related mcdr docs as well

I've done this in https://github.com/MCDReforged/MCDReforged/pull/334

**Pull request merged**
